name: CI/CD for Flask App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    # - name: Set up Python
    #   uses: actions/setup-python@v4
    #   with:
    #     python-version: '3.10'

    # - name: Install Dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install -r app/requirements.txt

    # - name: Run Tests
    #   run: |
    #     pytest

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    # - name: Log in to Docker Hub
    #   run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # - name: Build Docker Image
    #   run: docker build -t puskr99/car-price-a3:latest .

    # - name: Push Docker Image
    #   run: docker push puskr99/car-price-a3:latest

    - name: Set up SSH and Deploy to Server
      run: |
        # Set up SSH key and config
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo "
        Host bazooka
          HostName bazooka.cs.ait.ac.th
          User st125098
          IdentityFile ~/.ssh/id_rsa

        Host ml2023
          HostName ml.brain.cs.ait.ac.th
          User st125098
          IdentityFile ~/.ssh/id_rsa
          ProxyJump bazooka
        " > ~/.ssh/config
        chmod 600 ~/.ssh/config

        # Deploy to the ml2023 server
        ssh -tt ml2023 << 'EOF'
        cd st125098/
        docker-compose down
        docker-compose pull
        docker-compose up -d
        EOF

